
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Oct 17 2021 10:42:40 IST (Oct 17 2021 05:12:40 UTC)

// Verification Directory fv/mod5_count 

module mod5_count(out, clk, rst);
  input clk, rst;
  output [2:0] out;
  wire clk, rst;
  wire [2:0] out;
  wire n_0, n_1, n_2, n_3;
  DFQZRM2RA \out_reg[2] (.CK (clk), .D (out[0]), .RB (n_0), .Q
       (out[2]));
  DFQZRM2RA \out_reg[1] (.CK (clk), .D (n_2), .RB (n_3), .Q (out[1]));
  MXB2M1RA g153(.A (n_1), .B (out[0]), .S (out[1]), .Z (n_2));
  AN2M2R g152(.A (out[1]), .B (n_3), .Z (n_0));
  NR2M2R g154(.A (rst), .B (out[2]), .Z (n_3));
  DFZRM2RA \out_reg[0] (.CK (clk), .D (n_1), .RB (n_3), .Q (out[0]),
       .QB (n_1));
endmodule

